apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: ${GITHUB_SHA}-${GITHUB_REF_NAME}-auto-k8s
spec:
  forProvider:
    network: us-central1
    # location: {{  .Values.project.location  }}
    autopilot:
      enabled: true
  writeConnectionSecretToRef:
    name: ${GITHUB_SHA}-${GITHUB_REF_NAME}-auto-kube
    namespace: default