apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: ${GITHUB_SHA}-${GITHUB_REF_NAME}-auto-k8s
spec:
  forProvider:
    network: ephemeral-testing
    location: us-central1
    autopilot:
      enabled: true
  writeConnectionSecretToRef:
    name: ${GITHUB_SHA}-${GITHUB_REF_NAME}-auto-kube
    namespace: default