apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: ${GITHUB_SHA}-${GITHUB_REF_NAME}-release-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.1"
    namespace: default
  providerConfigRef:
    name: ${GITHUB_SHA}-${GITHUB_REF_NAME}-auto-k8s-helm-provider-config