apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: {{  .Values.github.sha  }}-{{  .Values.github.branch  }}-release-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.1"
    namespace: default
  providerConfigRef:
    name: {{  .Values.github.sha  }}-{{  .Values.github.branch  }}-auto-k8s-helm-provider-config