apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: main-2162621124-release-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.1"
    namespace: default
  providerConfigRef:
    name: main-2162621124-auto-k8s-helm-provider-config