apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: main-2162621124-auto-k8s
spec:
  forProvider:
    network: ephemeral-testing
    location: us-central1
    autopilot:
      enabled: true
  writeConnectionSecretToRef:
    name: main-2162621124-auto-kube
    namespace: default

# 21626211244d65b6c4752b37424b55aed62a86a6cbc910a3ac-main-auto-kube