---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: 64a56e6a15720fc4bf0018fcaa83de5c9463190f-main-auto-k8s-helm-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      name: 64a56e6a15720fc4bf0018fcaa83de5c9463190f-main-auto-kube
      namespace: default
      key: kubeconfig
  identity:
    type: GoogleApplicationCredentials
    source: Secret
    secretRef:
      name: gcp-creds
      namespace: crossplane-system
      key: creds