apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: 64a56e6a15720fc4bf0018fcaa83de5c9463190f-main-release-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.1"
    namespace: default
  providerConfigRef:
    name: 64a56e6a15720fc4bf0018fcaa83de5c9463190f-main-auto-k8s-helm-provider-config