apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: 7d2a3920e7643084cb690519b69ef21198845b6e-main-release-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.1"
    namespace: default
  providerConfigRef:
    name: 7d2a3920e7643084cb690519b69ef21198845b6e-main-auto-k8s-helm-provider-config