---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  # name: ${GITHUB_REF_NAME}-${GITHUB_RUN_ID}-auto-k8s-helm-provider-config
  name: argocd-testing-auto-k8s-helm-provider-config
spec:
  credentials:
    source: Secret
    secretRef:
      # name: ${GITHUB_REF_NAME}-${GITHUB_RUN_ID}-auto-kube
      name: argocd-testing-auto-kube
      namespace: default
      key: kubeconfig
  identity:
    type: GoogleApplicationCredentials
    source: Secret
    secretRef:
      name: gcp-creds
      namespace: crossplane-system
      key: creds