apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: argocd-testing-release-ingress-nginx
  # name: ${GITHUB_REF_NAME}-${GITHUB_RUN_ID}-release-ingress-nginx
spec:
  forProvider:
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: "4.0.1"
    namespace: default
  providerConfigRef:
    name: argocd-testing-auto-k8s-helm-provider-config
    # name: ${GITHUB_REF_NAME}-${GITHUB_RUN_ID}-auto-k8s-helm-provider-config