apiVersion: batch/v1
kind: Job
metadata:
    name: main-ephemeral-test-2
    # generateName: main-ephemeral-test-
    namespace: main-ephemeral-ns
spec:
  template:
    spec:
      containers:
      - image: curlimages/curl:7.82.0
        name: main-test-runner
        resources:
          requests:
            cpu: 100m
            memory: 100M
        command: ["/usr/bin/curl"]
        args: ["main-nginx-service:80"]
      restartPolicy: OnFailure